recorder:
  output_dir: "recordings"
  duration: 10  # Duration of the recording in seconds
  sample_rate: 16000  # Sample rate in Hz
  channels: 8
  gain: 1  # Gain applied to all channels
  labels_file: "labels.csv"  # File where labels will be stored

hardware1:
  type: "ReSpeaker"
  device_id: 2  # Device ID for Hardware 1
  channels: 6  # Number of channels for Hardware 1
  gain: 1.0  # Gain for Hardware 1 
  sample_rate: 16000  # Sample rate in Hz

hardware2:
  type: "MiniDSP"
  device_id: 3  # Device ID for hardware 2
  channels: 8  # Number of channels for hardware 2
  gain: 1  # Gain for hardware 2
  sample_rate: 16000  # Sample rate in Hz

experiment_meta:
  experiment_id: "exp10"  # Unique experiment identifier
  experiment_type: "typeA"  # Type of experiment (e.g., "typeA")
  run_date: "2024-11-26"  # Date of the experiment
  sample_count: 1  # Number of samples to record
  doa_range: [0, 360]  # Range of DOA in degrees
  elevation_range: [-90, 90]  # Range of elevation angles in degrees
  frequency_range: [20, 20000]  # Frequency range
  category_list: ["speech", "noise", "music"]  # List of categories for the experiment
  doa: 80  # Example: Direction of Arrival for this experiment
  elevation: 0  # Example: Elevation for this experiment
  selected_categories:  # Categories selected for the current experiment
    - "horn",
  category: "horn"
  frequency: 333 # Frequency range in Hz
  amplitude: 1  # Amplitude range


# Device selection for the experiment
selected_device: "hardware1"  # Choose between 'hardware1' or 'hardware2'


