defaults:
  - recorder: default_recorder
  - hardware1: default_hardware1
  - experiment_meta: default_experiment_meta

# Shared configurations for recorder
recorder:
  output_dir: "recordings"
  duration: 5
  sample_rate: 48000
  channels: 4
  gain: 1.0

# Default hardware configuration
hardware1:
  type: "ReSpeaker"
  device_id: 1
  channels: 6
  gain: 1.0

# Default experiment metadata
experiment_meta:
  experiment_id: "exp01"
  experiment_type: "test"
  run_date: "2024-11-26"
  sample_count: 1
  doa_range:
    min: 0
    max: 360
  elevation_range:
    min: -90
    max: 90
  frequency_range:
    min: 20
    max: 2000
  amplitude_range:
    min: 0.1
    max: 1.0
  categories:
    - "default"
  selected_categories:
    - "default"
  doa: 0
  elevation: 0
  frequency: 100
  amplitude: 0.5
