# default_experiment_meta.yaml
experiment_id: "default_exp"  # Default experiment identifier
experiment_type: "generic"  # Default experiment type
run_date: "2024-01-01"
sample_count: 5  # Default number of samples to record
doa_range:
  min: 0
  max: 360
elevation_range:
  min: -90
  max: 90
frequency_range:
  min: 20
  max: 2000
amplitude_range:
  min: 0.1
  max: 1.0
categories:
  - "horn"
  - "music"
  - "bird"
  - "noise"
selected_categories:
  - "horn"
doa: 30
elevation: 0
frequency: 1000
amplitude: 1.0
